services:
  - type: web
    name: contabilidadeplanning
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contabilidade-db
          property: connectionString
